// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace app_iMeet {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ConnectViewController")]
	public partial class ConnectViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_joinButton;
		
		private MonoTouch.UIKit.UITextField __mt_phoneTxt;
		
		private MonoTouch.UIKit.UILabel __mt_phoneLbl;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("joinButton")]
		private MonoTouch.UIKit.UIButton joinButton {
			get {
				this.__mt_joinButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("joinButton")));
				return this.__mt_joinButton;
			}
			set {
				this.__mt_joinButton = value;
				this.SetNativeField("joinButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("phoneTxt")]
		private MonoTouch.UIKit.UITextField phoneTxt {
			get {
				this.__mt_phoneTxt = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("phoneTxt")));
				return this.__mt_phoneTxt;
			}
			set {
				this.__mt_phoneTxt = value;
				this.SetNativeField("phoneTxt", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("phoneLbl")]
		private MonoTouch.UIKit.UILabel phoneLbl {
			get {
				this.__mt_phoneLbl = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("phoneLbl")));
				return this.__mt_phoneLbl;
			}
			set {
				this.__mt_phoneLbl = value;
				this.SetNativeField("phoneLbl", value);
			}
		}
	}
}
