// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace app_iMeet {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SignUpViewController")]
	public partial class SignUpViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextField __mt_passTxt;
		
		private MonoTouch.UIKit.UITextField __mt_phoneTxt;
		
		private MonoTouch.UIKit.UIButton __mt_registerButton;
		
		private MonoTouch.UIKit.UITextField __mt_userTxt;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("passTxt")]
		private MonoTouch.UIKit.UITextField passTxt {
			get {
				this.__mt_passTxt = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("passTxt")));
				return this.__mt_passTxt;
			}
			set {
				this.__mt_passTxt = value;
				this.SetNativeField("passTxt", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("phoneTxt")]
		private MonoTouch.UIKit.UITextField phoneTxt {
			get {
				this.__mt_phoneTxt = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("phoneTxt")));
				return this.__mt_phoneTxt;
			}
			set {
				this.__mt_phoneTxt = value;
				this.SetNativeField("phoneTxt", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("registerButton")]
		private MonoTouch.UIKit.UIButton registerButton {
			get {
				this.__mt_registerButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("registerButton")));
				return this.__mt_registerButton;
			}
			set {
				this.__mt_registerButton = value;
				this.SetNativeField("registerButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("userTxt")]
		private MonoTouch.UIKit.UITextField userTxt {
			get {
				this.__mt_userTxt = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("userTxt")));
				return this.__mt_userTxt;
			}
			set {
				this.__mt_userTxt = value;
				this.SetNativeField("userTxt", value);
			}
		}
	}
}
